# 端口
server:
  port: ${SERVER_PORT}

spring:
  # druid 数据源
  datasource:
    druid:
      driver-class-name: ${MYSQL_DRIVER}
      url: jdbc:mysql://${MYSQL_HOST}:3306/${DATABASE_NAME}?characterEncoding=UTF8
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    banner-mode: OFF
  config:
    import: optional:file:.env[.properties]

# 日志配置文件
logging:
  config: classpath:log4j2-boot-dev.xml