# 应用环境
spring:
  profiles:
    active: @profile.active@
  datasource:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  # spring-data-jpa
  jpa:
    generate-ddl: false
    database: mysql

  # flyway
  flyway:
    enabled: true
    encoding: UTF-8