# 应用环境
spring:
  profiles:
    active: @profile.active@
  datasource:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  # spring-data-jpa
  jpa:
    generate-ddl: false
    database: mysql
  # swagger3和spring版本冲突
  # Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # flyway
  flyway:
    enabled: true
    encoding: UTF-8

  #设置单个文件的大小
  servlet:
    multipart:
      max-file-size: 50MB
  #设置单次请求的文件的总大小
      max-request-size: 50MB

# 本地文件上传地址
hellovie:
  protocol: http
  file:
    root-path: D:/local-storage
    avatar-path: /avatar
    default-path: /default
    cover-path: /cover